[package]
name = "solana-attestation-service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
pinocchio = "0.7.1"
pinocchio-log = "0.3.0"
pinocchio-pubkey = "0.2.2"
pinocchio-system = "0.2.1"
solana-program = "2.1.13"

[dev-dependencies]
borsh = "1.5.5"
solana-program-test = "2.1.13"
solana-sdk = "2.1.13"
tokio = "1.43.0"
